# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1h8h6256hyv4vmh19xvfnvl5j7bhsq61ay4lza3khz3r0wrdgqxl";
    aarch64-linux = "0wnjbl0d83vwkhi21f90waxyick2f8n0j4krvjd3zwn9308w8nzw";
    aarch64-darwin = "18kcw5m02p3syn9pw7famky85nbwbjhfy3nc4mx8f8158xyc6gpp";
  };

  urlMap = {
    x86_64-linux = "https://github.com/tenequm/homebrew-tap/releases/download/pond-v0.2.6/pond-x86_64-unknown-linux-gnu.tar.xz";
    aarch64-linux = "https://github.com/tenequm/homebrew-tap/releases/download/pond-v0.2.6/pond-aarch64-unknown-linux-gnu.tar.xz";
    aarch64-darwin = "https://github.com/tenequm/homebrew-tap/releases/download/pond-v0.2.6/pond-aarch64-apple-darwin.tar.xz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "pond";
  version = "0.2.6";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./pond $out/bin/pond
  '';

  meta = {
    description = "Lossless storage and hybrid search for AI agent sessions, across every agentic client.";
    homepage = "https://github.com/tenequm/homebrew-tap";
    license = lib.licenses.asl20;
    mainProgram = "pond";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-linux"
    ];
  };
}
