# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1hvhyw9my341z91bgqdrnjwdlp86f7a8g4ip807ng67czayxn450";
    aarch64-linux = "0r92mbbsbcd8103qr6mnzcbfsxjmgs8nnfmvcbfkn85gln89aizd";
    aarch64-darwin = "0pw6a6vxpmyr69iqz4chgipdnb2qk20lcvvpsabsmn8mp62cxbni";
  };

  urlMap = {
    x86_64-linux = "https://github.com/tenequm/homebrew-tap/releases/download/pond-v0.2.2/pond-x86_64-unknown-linux-gnu.tar.xz";
    aarch64-linux = "https://github.com/tenequm/homebrew-tap/releases/download/pond-v0.2.2/pond-aarch64-unknown-linux-gnu.tar.xz";
    aarch64-darwin = "https://github.com/tenequm/homebrew-tap/releases/download/pond-v0.2.2/pond-aarch64-apple-darwin.tar.xz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "pond";
  version = "0.2.2";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./pond $out/bin/pond
  '';

  meta = {
    description = "Lossless storage and hybrid search for AI agent sessions, across every agentic client.";
    homepage = "https://github.com/tenequm/homebrew-tap";
    license = lib.licenses.asl20;
    mainProgram = "pond";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-linux"
    ];
  };
}
