# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "0x0w0cmb0374pcqy45zdccsvfcb7g121fzzmv0rkhrp9d33awd77";
    aarch64-linux = "0crwv8gfv70lrg1g0lbqinn9zz07pimhmg5170zm45ab15alxfp6";
    aarch64-darwin = "0dk6vfxczzvy3hzg768qdp5kcrhm6dg6gm9wlww43ibgjlqiyavr";
  };

  urlMap = {
    x86_64-linux = "https://github.com/tenequm/homebrew-tap/releases/download/pond-v0.2.3/pond-x86_64-unknown-linux-gnu.tar.xz";
    aarch64-linux = "https://github.com/tenequm/homebrew-tap/releases/download/pond-v0.2.3/pond-aarch64-unknown-linux-gnu.tar.xz";
    aarch64-darwin = "https://github.com/tenequm/homebrew-tap/releases/download/pond-v0.2.3/pond-aarch64-apple-darwin.tar.xz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "pond";
  version = "0.2.3";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./pond $out/bin/pond
  '';

  meta = {
    description = "Lossless storage and hybrid search for AI agent sessions, across every agentic client.";
    homepage = "https://github.com/tenequm/homebrew-tap";
    license = lib.licenses.asl20;
    mainProgram = "pond";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-linux"
    ];
  };
}
